### ISSUE TITLE
Can't fetch....

### ISSUE THREAD

**Issue by nigelhorne** [thedumbterminal/HTML-Form-XSS#1]
I can't get it to work.  Please advise.

./check.pl https://www.bandsman.co.uk/cgi-bin/page.fcgi?page=mailto
Found form:
POST https://www.bandsman.co.uk/cgi-bin/page.fcgi?page=mailto#
  action=send                    (hidden readonly)
  yname=                         (text)
  yemail=                        (email)
  message=                       (textarea)
  <NONAME>=submit                (submit)
Test it (y/n)?y
Can't fetch https://www.bandsman.co.uk/cgi-bin/page.fcgi?page=mailto# at ../lib/HTML/Form/XSS.pm line 124.
    HTML::Form::XSS::do_audit(HTML::Form::XSS=HASH(0x7fc4e3829db0), HTML::Form=HASH(0x7fc4e1079c20)) called at ./check.pl line 26
Checking... 302

**Comment by thedumbterminal** [comment]
Thanks for the bug report.

It seems the site you are testing employs: http://spambot.sourceforge.net/

I've now added a valid user agent request header when testing a form, which bypasses the spambot checks.

If you pull down the latest master version of this repo and let me know how it goes.

Thanks

**Comment by thedumbterminal** [comment]
Closing this as the issue should now be resolved in: https://github.com/thedumbterminal/HTML-Form-XSS/releases/tag/v1.0
